### ISSUE TITLE
USB-C Dock Gen2 FW packages (usbcg2dkfw1118_2, usbcg2dkfw1120) hanging during `Get-LSUpdate`

### ISSUE THREAD

**Issue by SynMaki** [jantari/LSUClient#73] opened 2023-03-13 13:10 UTC
### Version

1.5.1

### Computer Model

All

### Problem

Currently we have problems with the update usbcg2dkfw1118_2_version.exe via LSU.

It seems that it does not want to install cleanly.

On **most models** the following message simply appears:
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:05:00.0238322
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:06:00.1898034
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:07:00.3896485
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:08:00.5626027

After that no more entries.

On **one model** I found more in the log:

Monday, 13. March 2023 09:30:35

Proxy :
ProxyCredential :
ProxyUseDefaultCredential : False
MaxExternalDetectionRuntime : 00:10:00
MaxExtractRuntime : 00:20:00
MaxInstallerRuntime : 00:20:00

WARNING: Process 'C:\Windows\TEMP\o502l2pl.wdr\hvm0dozl.jqb\usbcg2dkfw1118_2_version.exe' has been running for 00:05:00.1464540
WARNING: Process 'C:\Windows\TEMP\o502l2pl.wdr\hvm0dozl.jqb\usbcg2dkfw1118_2_version.exe' has been running for 00:06:00.2515020
WARNING: Process 'C:\Windows\TEMP\o502l2pl.wdr\hvm0dozl.jqb\usbcg2dkfw1118_2_version.exe' has been running for 00:07:00.3340044
WARNING: Process 'C:\Windows\TEMP\o502l2pl.wdr\hvm0dozl.jqb\usbcg2dkfw1118_2_version.exe' has been running for 00:08:00.4157345
WARNING: Process 'C:\Windows\TEMP\o502l2pl.wdr\hvm0dozl.jqb\usbcg2dkfw1118_2_version.exe' has been running for 00:09:00.4422964
WARNING: Process has exceeded the configured runtime limit of 00:10:00
WARNING: Process has windows open, this can help troubleshoot why it timed out:
WARNING: Process has windows open, this can help troubleshoot why it timed out:
WARNING: Process has windows open, this can help troubleshoot why it timed out:
WARNING: Killing process 12984 'cmd' due to exceeding time limit ...
WARNING: Killing process 12588 'conhost' due to exceeding time limit ...
WARNING: Killing process 12528 'FWU' due to exceeding time limit ...
WARNING: Killing process 3400 'FWUpdateTool' due to exceeding time limit ...
WARNING: Killing process 13160 'usbcg2dkfw1118_2_version' due to exceeding time limit ...
WARNING: Killing process 12452 'usbcg2dkfw1118_2_versionsfx' due to exceeding time limit ...
WARNING: Killing process 13112 'VmmDPTool64' due to exceeding time limit ...
WARNING: Killing process 8392 'wscript' due to exceeding time limit ...

The problem is that the processes FWU & FWUpdateTool must be closed manually and then the firmware must be updated manually via usbcg2dkfw1118_2_version.exe.
![image](https://user-images.githubusercontent.com/29663382/224711588-1dbece3c-4401-498d-b104-483a350588c2.png)
![image](https://user-images.githubusercontent.com/29663382/224711662-818d4d53-8141-4dff-aab4-d067f84d0665.png)

This is the dock "USB-C Gen2 40AS". 

Also important, there doesn't seem to be issues with all of them, yet there are some.

Can you help here at best or is it once again due to poorly created Lenovo updates?

**Comment by wgriffinArch** [comment] 2023-03-13 13:27
I concur.  This weekend I worked to update 1800+ machines and quite a few would hang.  One for up to 2 hours.  I'd be happy to gather data if needed next time i have a Change control for the work.

**Comment by jantari** [comment] 2023-03-13 17:48
> On most models the following message simply appears:
>
> WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:05:00.0238322
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:06:00.1898034
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:07:00.3896485
WARNING: Process 'C:\WINDOWS\TEMP\jxy4454p.2lu\gnfot5ri.1xo\usbcg2dkfw1118_2_version.exe' has been running for 00:08:00.5626027
>
> After that no more entries.

That looks like the process did eventually finish after 8+ minutes. If you could give me some model numbers where this happened I can try to reproduce this on a real machine. Is the "USB-C Gen2 40AS" dock connected while this runs or not? Or sometimes yes sometimes no?

Also, if you can reproduce this with `Get-LSUpdate -Verbose -Debug` that would be great as there's a lot of additional details in the debug output.

@wgriffinArch The machines should definitely not hang that long at this point unless you are using an older version of LSUClient (one before 1.5.0). More recent versions of LSUClient will kill external detection processes after 10 minutes by default. Check to see if you're using an outdated version please and retry with the latest.

**Comment by wgriffinArch** [comment] 2023-03-13 17:55
I was using v1.5.1
The model that ran for 2 hours is a 20QD000LUS.

I started a transcription at the beginning of the script and here is a portion....

VERBOSE: Installing package n2hdr35w ...
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:05:00.0631418
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:06:00.2160740
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:07:00.3573137
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:08:00.5349774
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:09:00.5879147
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:10:00.6869739
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:11:00.7201102
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:12:00.8793736
WARNING: Process 'C:\WINDOWS\TEMP\LSUPackages\n2hdr35w\installer.exe' has been running for 00:13:01.0690935

it just kept going til i came back, and killed the script.

**Comment by wgriffinArch** [comment] 2023-03-13 17:59
I new to github and i'm sure this isn't the right place for it, but the option to pass a parameter to skip battery health checks on bios updates would be awesome.  I have a few that will never update for that reason.

i have the call the installer with a switch to skip it.
winuptp64.exe with the -sp switch for example...

**Comment by jantari** [comment] 2023-03-13 18:11
@wgriffinArch that is actually a different problem from what @SynMaki reported then, for them `usbcg2dkfw1118_2_version.exe` which is part of the package [`usbcg2dkfw1118_2`](https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1118_2_2_.xml) is taking a very long time during the update search phase (Get-LSUpdate).

You have a different package `n2hdr35w` and in your case it's also not the detection but the installation process that's hanging.

Therefore it would be best if you open two separate issues for the install issue with n2hdr35w and for the bios update battery check skip. Else it gets hard to keep track of and link others to a specific issue later.

**Comment by SynMaki** [comment] 2023-03-14 07:30
Alright, got the Debug:
[LSUClientDEBUG.txt](https://github.com/jantari/LSUClient/files/10965327/LSUClientDEBUG.txt)

While it is on:
  File: C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe
  Arguments: /usbcg2dkfw1118_2_versionsfx.exe /check
  WorkingDirectory: C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5
DEBUG: Added runspace process 3472 to job: True
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:05:00.1419230
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:06:00.2639676
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:07:00.4219375
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:08:00.4492247
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:09:00.5054848
WARNUNG: Process has exceeded the configured runtime limit of 00:10:00

These proceses are running:
![image](https://user-images.githubusercontent.com/29663382/224926461-14f5beaa-0d9b-4487-8f06-b72b098cec75.png)


After that, i run the FWupdater manually which gave out this message:
![image](https://user-images.githubusercontent.com/29663382/224926738-9fadf336-ad2a-4fc4-a859-900d88d3c68e.png)

Just pressing ok and it goes on:
![image](https://user-images.githubusercontent.com/29663382/224926874-8dc807bd-bfce-4a0e-bba9-a821d83941d8.png)


The main issue is that the external **monitors will loose connection until the FW update is manually done** which causes us some pain at the moment.
a restart, reset or whatever will not help.

**Comment by jantari** [comment] 2023-03-14 19:21
So is there an issue with installing that firmware update using LSUClient as well or is the problem only during the detection process of `Get-LSUpdate`?

I ask because you say that you run the FWupdater manually.

**Comment by SynMaki** [comment] 2023-03-14 20:27
Yes there is an issue.
The LSUClient triggers the firmware update and sets the dock in an unusable state.
With unusable state i mean that there will bi no video output through the dock once the update process has failed via LSUclient
As you see in the debug log, the lsu client starts the update but ends it after 10 mins since there probably is an open window.

since the lsuclient cannot handle it, i started the update manually afterwards. My guess is that the LSUClient hangs on the message „can not find synaptics…..“ message which i attached in the screenshot in my previous post.

**Comment by jantari** [comment] 2023-03-16 22:47
This problem is odd because at the stage where LSUClient hangs for you, both in the debug log:

<details>

```
...
AUSFÜHRLICH: Parsing dependencies for package: usbcg2dkfw1118_2 (ThinkPad USB-C Dock Gen2 FW Package - 10 (1809 or Later)/11 (21H2 or Later))
DEBUG: - |> Node: Dependencies
DEBUG: - - |> Node: And
DEBUG: - - - |> Node: Or
DEBUG: - - - - |> Node: And
DEBUG: - - - - - |> Node: _OS
DEBUG: - - - - - < Returning 1 from node _OS
DEBUG: - - - - - |> Node: _CPUAddressWidth
DEBUG: - - - - - [ Got: 64, Expected: 64 ]
DEBUG: - - - - - < Returning 1 from node _CPUAddressWidth
DEBUG: - - - - - |> Node: _WindowsBuildVersion
DEBUG: - - - - - [ Got: 19042, Expected: 17763^ ]
DEBUG: - - - - - < Returning 1 from node _WindowsBuildVersion
DEBUG: - - - - Tree was AND: Results: 1 1 1
DEBUG: - - - - < Returning 1 from node And
DEBUG: - - - - |> Node: _OS
DEBUG: - - - - < Returning 0 from node _OS
DEBUG: - - - Tree was OR: Results: 1 0
DEBUG: - - - < Returning 1 from node Or
DEBUG: - - - |> Node: _ExternalDetection
DEBUG: Starting external process:
  File: C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe
  Arguments: /usbcg2dkfw1118_2_versionsfx.exe /check
  WorkingDirectory: C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5
DEBUG: Added runspace process 3472 to job: True
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:05:00.1419230
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:06:00.2639676
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:07:00.4219375
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:08:00.4492247
WARNUNG: Process 'C:\Windows\TEMP\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe' has been running for 00:09:00.5054848
WARNUNG: Process has exceeded the configured runtime limit of 00:10:00
...
```
</details>

and in your screenshot:

<details>

![image](https://user-images.githubusercontent.com/29663382/224926461-14f5beaa-0d9b-4487-8f06-b72b098cec75.png)
</details>

the firmware update is not supposed to be installed at all, so the dock should not be affected. This step / process is just to determine whether the firmware is installed already, or whether it still needs to be installed. Basically it only compares the version of the current firmware of the dock. This is, as the log shows, the "Parsing dependencies" stage of `Get-LSUpdate`. Not the actual installation that would be done later with `Install-LSUpdate`.

Yesterday I ran LSUClient against a lot of machines to try and see if I get the same problem on any of them, but all of them that had this update available ran past this step normally - some laptops with the dock connected and some without it, all worked without issues.

Do you get the same endless hanging or maybe an error message when you download these two files:

https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1118_2_version.exe
https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1118_2_versionsfx.exe

to the same directory and then run this yourself on one of the affected machines:

```
$p = Start-Process usbcg2dkfw1118_2_version.exe -Wait -PassThru -ArgumentList '/usbcg2dkfw1118_2_versionsfx.exe /check'
$p | Select-Object ExitCode, StartTime, ExitTime
```

**Comment by SynMaki** [comment] 2023-03-17 07:39
so i placed both files in the folder and ran the Script in SYSTEM Context:

`Start-Transcript -Path C:\XXXX\Logs\DOCKFW.log
$p = Start-Process "C:\temp\tkajhlnl.ypa\h4pkwipm.ma5\usbcg2dkfw1118_2_version.exe" -Wait -PassThru -ArgumentList '/usbcg2dkfw1118_2_versionsfx.exe /check'
$p | Select-Object ExitCode, StartTime, ExitTime
Stop-Transcript`

Seems like ill never get any feedback from it. it just runs and runs. But, it doesent trigger any Process called FWU or FWUpdate.

Theres nothing in the log, therefore ill have nothing to share here. 

Im still assuming that theres the "Can not find Synaptics MST DP hub IC" message in the background which cases this. Ill had another Laptop without LSUCllient but with the Lenovo System Update. It seems like it wanted to update the dock as well, the only difference, the System Update was able to display the message "Can not find Synaptics MST DP hub IC" to the current logged in user.

**Comment by SynMaki** [comment] 2023-03-17 10:18
To start the ise in System i used psexec:
psexec -i -s powershell_ise.exe

Just did that, same -> Just hangs like that forever.
ID is 1
![image](https://user-images.githubusercontent.com/29663382/225877396-dfc7b2f7-0bee-46fc-965e-7b3db5118f9d.png)

**Comment by jantari** [comment] 2023-03-18 14:28
I have still not been able to reproduce this problem on any system that has this dock so far, I'm guessing it only happens on specific configurations as some of the people in these threads you found suggest there could be a dependency on a specific BIOS or Graphics driver version that should be installed first:

> https://forums.lenovo.com/t5/ThinkPad-X-Series-Laptops/Can-not-find-Synaptics-MST-DP-hub-IC/m-p/5158179
https://forums.lenovo.com/t5/ThinkPad-T400-T500-and-newer-T-series-Laptops/Can-not-find-Synaptics-MST-DP-hub-IC/m-p/5153067
https://forums.lenovo.com/t5/Displays-Options-and-Accessories/Can-not-find-Synaptics-MST-DP-HUB-IC/m-p/5197048
https://www.reddit.com/r/thinkpad/comments/y3yzcx/thinkpad_usbc_docking_station_as40_external/

In LSUClient 1.5.3 I have added additional debug information about long-running (potentially stuck) processes like yours here, so if you could reproduce this problem again with LSUClient version 1.5.3 and with `-Verbose -Debug` output enabled and send that log I hope it will help understand the cause.

**Comment by SynMaki** [comment] 2023-03-21 07:10
So, lenovo just released the Firmware usbcg2dkfw1120_2 Update. 
That means i cannot thest it any further. It seems like the new Firmware is working fine.

I can definetely tell, that the new Update doesent prompt the message " Can not find Synaptics MST DP hub IC " anymore.

I started the old FW update manually --> message appears
I started the new FW Update manually --> message does not appear
I started the old FW update manually again --> message appears

Also, a client which i fixed last week installed the new Dock FW just fine:

nStart der Windows PowerShell-Aufzeichnung
Startzeit: 20230320130507
Benutzername: XXXXX-INTRA\SYSTEM
RunAs-Benutzer: XXXX-INTRA\SYSTEM
Konfigurationsname: 
Computer: XXXXXX20186 (Microsoft Windows NT 10.0.19042.0)
Hostanwendung: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -windowstyle hidden C:\Windows\RoamingPlus\Tools\LSUClient\UpdateDriversUnattended.ps1
Prozess-ID: 10040
PSVersion: 5.1.19041.2364
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.2364
BuildVersion: 10.0.19041.2364
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Die Aufzeichnung wurde gestartet. Die Ausgabedatei ist "C:\XXXX\Logs\LSUClient.txt".

Montag, 20. März 2023 13:05:07

Proxy                       :
ProxyCredential             :
ProxyUseDefaultCredential   : False
MaxExternalDetectionRuntime : 00:10:00
MaxExtractRuntime           : 00:20:00
MaxInstallerRuntime         : 00:20:00

AUSFÜHRLICH: Processing package 'usbcg2dkfw1120_2 - ThinkPad USB-C Dock Gen2 FW Package - 10 (1809 or Later)/11 (21H2 or Later)'
AUSFÜHRLICH: Destination directory did not exist, created it: 'C:\ProgramData\LSUTemp\usbcg2dkfw1120_2'
AUSFÜHRLICH: Starting download of 'https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1120_2_2_.xml'
AUSFÜHRLICH: Starting download of 'https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1120_2.exe'
AUSFÜHRLICH: Starting download of 'https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1120_2.txt'
AUSFÜHRLICH: Starting download of 'https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1120_2_version.exe'
AUSFÜHRLICH: Starting download of 'https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1120_2_versionsfx.exe'
AUSFÜHRLICH: Installing package usbcg2dkfw1120_2 ...
AUSFÜHRLICH: MaxInstallerRuntime of 00:20:00 will not be enforced for this package because it appears to be a BIOS or firmware update

ID             : usbcg2dkfw1120_2
Title          : ThinkPad USB-C Dock Gen2 FW Package - 10 (1809 or Later)/11 (21H2 or Later)
Type           : Firmware
Success        : True
FailureReason  :
PendingAction  : REBOOT_MANDATORY
ExitCode       : 0
StandardOutput : {}
StandardError  : {}
LogOutput      : {}
Runtime        : 00:01:00.6262830
**********************
Ende der Windows PowerShell-Aufzeichnung
Endzeit: 20230320130716
**********************

**Comment by jantari** [comment] 2023-03-22 20:18
Ok, we couldn't find out what exactly caused this message but if Lenovo fixed it that's even better ^^

In case the new package version isn't available for all computer models yet I would recommend filteing out the previous one so that it doesn't cause any more problems: `$updates | Where-Object ID -ne 'usbcg2dkfw1118_2'`

I'm going to close this issue as I feel like there's little more we can do. Sometimes the official packages are just going to have some issues unfortunately. The extended logging on 1.5.3 should help identify these even earlier.

**Comment by jantari** [comment] 2023-03-30 20:38
Actually I'm not sure if this problem is really in the past.

When testing something else unrelated I saw in the logs the new package `usbcg2dkfw1120_2` hanging on a model 20X7, but on a second run of the same script only a minute later the `usbcg2dkfw1120_2_version.exe` did not hang anymore.

**Comment by SynMaki** [comment] 2023-05-05 06:23
I have meanwhile excluded the dock updates with the following command. Currently, there also seem to be problems with the TB firmware.
Model number: 20YQ, 20YR
Thunderbolt Workstation dock 4.

Let me know if you want me to test anything
[LSUClient.txt](https://github.com/jantari/LSUClient/files/11403740/LSUClient.txt)

**Comment by jantari** [comment] 2023-06-20 20:21
Since my last comment I haven't had this issue reproduce again for me, and no more reports here either.

I think it must've been a problem with the external detection command of the package. With a `MaxExternalDetectionRuntime` 
configured the hanging process was terminated as expected for me and everything worked the second time around.

I'm going to close the issue as I don't think it's an issue with LSUClient and I don't think I can do much more to mitigate or prevent it.

**Closed by jantari** 2023-06-20 20:21 UTC
Labels: bug
