### ISSUE TITLE
Flash.cmd only accepting first parameter and older wflash2.exe versions

### ISSUE THREAD

**Issue by ChrisQuestionMark** [jantari/LSUClient#9] opened 2019-09-05 15:50 UTC
### Infos:

* Used Module Version: 1.0.2
* Lenovo Model number: 10E9000

---

**Comment by jantari** [comment] 2019-09-05 20:07
Is the problem you're seeing that `Install-LSUpdate` hangs forever on installing the BIOS Update without doing anything?

**Comment by ChrisQuestionMark** [comment] 2019-09-05 20:14
Correct,
By using ProcExp I was able to tell what process it was waiting on and its command line arguments and and tracked it down to this issue

**Comment by jantari** [comment] 2019-09-06 06:00
Thanks, I was able to reproduce and diagnose the issue.

This is caused by older `wflash2.exe` versions not supportingt the `/sccm` (suppress reboot) parameter which I use. When you supply `wflash2.exe` an unknown parameter it just shows you some usage help which would not be a problem - however instead of simply exiting with an error code it then pauses and waits for you to press a key before it exits.

This is what causes the imdefinite hanging.

I'm looking for a fix

**Comment by jantari** [comment] 2019-10-18 14:24
Hi, just wanted to update you on this.

After trying many things I've found a pretty non-janky solution to this that I feel comfortable rolling out to the world.

I'll do a wee bit more testing, but then Version 1.0.3 is just about ready for release and it will include the fix for this issue: it will detect whether the version of wflash2 that Lenovo includes in the BIOS Update package supports the `/sccm` parameter and if it doesn't it will say so and skip the update - but no more hanging!

**Closed** 2019-10-21 19:40 UTC
Labels: bug

**Comment by jantari** [comment] 2019-10-21 19:46
Version 1.0.3 is released here on GitHub and includes this fix: https://github.com/jantari/LSUClient/releases/tag/v1.0.3

Will hit the PowerShell Gallery later this week!
